apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-app
  namespace: payments
  labels:
    app: payments-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments-app
  template:
    metadata:
      labels:
        app: payments-app
    spec:
      containers:
      - name: web
        image: nginx:alpine
        ports:
        - containerPort: 80
