# ArgoCD App: Deploy payments tenant infrastructure/policies
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Deploy early alongside common infra
spec:
  project: default
  source:
    repoURL: https://github.com/NguyenAnhHoangIT/CD_Learning.git
    path: tenants/payments
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: payments
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
