apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Install at wave 0 alongside other infra controllers
spec:
  project: default
  source:
    repoURL: 'https://stakater.github.io/stakater-charts'
    chart: reloader
    targetRevision: 1.0.118 # Stable version of the Reloader Helm chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
