apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-creds
  namespace: demo
spec:
  refreshInterval: 1m # Cứ mỗi 60 giây ESO sẽ lên AWS check xem mật khẩu có đổi không
  secretStoreRef:
    name: aws-store
    kind: SecretStore
  target:
    name: db-secret # Đây là tên K8s Secret sẽ được sinh ra tự động trong cụm
  data:
    - secretKey: password # Key hiển thị trong K8s Secret
      remoteRef:
        key: demo/db/password # Key thực tế nằm trên AWS Secrets Manager